### ISSUE TITLE
Capture terminal wizard screenshots for getting started page

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/pl-website-eleventy#3]
Capture and display screenshots of terminal breaking down step by step the stages of the wizard.

**Comment by bradfrost** [comment]
Markdown syntax for images:

```
![alt text](/path/to/image.png)
```

https://www.markdownguide.org/basic-syntax/

**Comment by bradfrost** [comment]
installation.md

**Comment by QuincyGow** [comment]
Just want to clarify here.  You'd like me to go through the terminal and break down what each step means, correct?  If I can get a kickstart conversation to just point me down the right path before I go off into the woods, I would greatly appreciate it.

<img width="1110" alt="Screen Shot 2019-12-30 at 4 43 13 PM" src="https://user-images.githubusercontent.com/48933977/71601899-91e86e00-2b23-11ea-97f7-7906d575bb41.png">
<img width="915" alt="Screen Shot 2019-12-30 at 4 41 20 PM" src="https://user-images.githubusercontent.com/48933977/71601900-91e86e00-2b23-11ea-9fa7-5032ec815939.png">

**Comment by QuincyGow** [comment]
Below is a sample of the color scheme "Novel" in Terminal (the app).  In order to get rid of my name and computer name I changed the settings in my computer to get a more generic name there.

Looked at other apps "Carbon" and "Terminalizer" but I think Licecap combined with the built-in terminal is the way to go.

**personal note** - Capture as GIFs, use preview to take out unnecessary frames.  Create MP4s from those gifs. 

<img width="569" alt="Screen Shot 2020-01-06 at 3 22 34 PM" src="https://user-images.githubusercontent.com/48933977/71846422-869fc000-3098-11ea-992c-dee878819696.png">

**Comment by QuincyGow** [comment]
https://www.google.com/search?q=solarized+dark&rlz=1C5CHFA_enUS872US872&sxsrf=ACYBGNQtt6N2Mz04_yAoXqfDtoXNnFm70g:1578683487188&tbm=isch&source=iu&ictx=1&fir=MPh6jJPV1N0MfM%253A%252CaqQDLTRmIWN9jM%252C_&vet=1&usg=AI4_-kTcetnzWfTipZcz6avJyYZCYxnUpg&sa=X&ved=2ahUKEwiUst2j3vnmAhWt2FkKHYmuCOMQ_h0wC3oECAsQBQ#imgrc=MPh6jJPV1N0MfM:

**Comment by QuincyGow** [comment]
Theme set up.  Even got the atomic design logo in the background.  However, I'm running into this (see picture) which is freezing up the process.  Attempting to solve next.
<img width="814" alt="Screen Shot 2020-01-17 at 9 36 14 AM" src="https://user-images.githubusercontent.com/48933977/72621448-413c8780-390f-11ea-9dae-4ba39fcf08ba.png">

**Comment by QuincyGow** [comment]
Just putting this full gif here for reference...
![SG1](https://user-images.githubusercontent.com/48933977/72623626-7fd44100-3913-11ea-828e-0e4e118ae078.gif)

**Comment by bradfrost** [comment]
closed via #22
